version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: esbuild
    versions:
    - 0.10.0
    - 0.10.1
    - 0.11.0
    - 0.11.10
    - 0.11.12
    - 0.11.13
    - 0.11.15
    - 0.11.2
    - 0.11.3
    - 0.11.5
    - 0.11.6
    - 0.11.9
    - 0.8.46
    - 0.8.48
    - 0.8.49
    - 0.8.50
    - 0.8.51
    - 0.8.52
    - 0.8.54
    - 0.8.55
    - 0.8.56
    - 0.8.57
    - 0.9.0
    - 0.9.2
    - 0.9.3
    - 0.9.5
    - 0.9.6
    - 0.9.7
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: ts-jest
    versions:
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: marked
    versions:
    - 1.2.8
    - 1.2.9
    - 2.0.0
    - 2.0.1
  - dependency-name: bili
    versions:
    - 5.0.5
  - dependency-name: nodemon
    versions:
    - 2.0.7
  - dependency-name: tape
    versions:
    - 5.1.1
  - dependency-name: prismjs
    versions:
    - 1.23.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.29.0
